### ISSUE TITLE
Ban User POST missing info for required user_id

### ISSUE THREAD

**Issue by johnebgood** [DmitryScaletta/twitch-api-swagger#1]
For https://twitch-api-swagger.surge.sh/#/Moderation/ban-user I noticed that ban user call was missing a required post parameter user_id. Can the script be modified to include required post parameters from the api documentation?

Thanks!
~John

**Comment by DmitryScaletta** [comment]
Looks like `user_id` has to be specified in the request body according the [docs](https://dev.twitch.tv/docs/api/reference/#ban-user)

![image](https://github.com/DmitryScaletta/twitch-api-swagger/assets/5096735/277c7a57-83e9-4c6d-a44d-7623de842753)

You can click "Schema" button in the request body section to see its shape

![image](https://github.com/DmitryScaletta/twitch-api-swagger/assets/5096735/60fa0058-cd0a-4811-96ee-d928f40e141e)
