### ISSUE TITLE
Errors in generated files: broken Enum, missing class

### ISSUE THREAD

**Issue by MircoL** [DmitryScaletta/twitch-api-swagger#2]
Hi,
thanks for your work, I really appreciate it and it is very useful.

However, when generating an API using `openapi-typescript-codegen`, I get some errors.

Command:

```sh
npx openapi \
	--input https://twitch-api-swagger.surge.sh/openapi.json \
	--output ./api/twitch-v2-client \
	--client axios \
	--name TwitchV2Clien
```

The errors are fixable by running these commands:
```sh
sed -i "s/= '',//g" ./api/twitch-v2-client/models/User.ts
echo 'export type Guest = any;' > ./api/twitch-v2-client/models/Guest.ts
```

User.ts:
```ts
export namespace User {
    /**
     * The type of user. Possible values are:
     *
     * * admin — Twitch administrator
     * * global\_mod
     * * staff — Twitch staff
     * * "" — Normal user
     */
    export enum type {
        ADMIN = 'admin',
        GLOBAL_MOD = 'global_mod',
        STAFF = 'staff',
        = '', //                                           <---------
    }
    /**
     * The type of broadcaster. Possible values are:
     *
     * * affiliate — An [affiliate broadcaster](https://help.twitch.tv/s/article/joining-the-affiliate-program target=)
     * * partner — A [partner broadcaster](https://help.twitch.tv/s/article/partner-program-overview)
     * * "" — A normal broadcaster
     */
    export enum broadcaster_type {
        AFFILIATE = 'affiliate',
        PARTNER = 'partner',
        = '', //                                         <---------
    }
}
```

GuestStarSession.ts:
```ts
import type { Guest } from './Guest'; // missing file
``` 

Is it possible to fix this? Thank you.

**Comment by DmitryScaletta** [comment]
Thanks for the report.
I fixed the `Guest` type.

I'm not sure about enums.
Twitch uses empty strings here:

<details>

![image](https://github.com/DmitryScaletta/twitch-api-swagger/assets/5096735/b3def077-8c91-4566-9561-69143577a885)

</details>

And `openapi-typescript-codegen` tries to use this empty string as a name in enum.
I think it's their issue that they can't handle empty enum values.

You can run something like this for example after codegen:
```bash
sed -i "s/= '',/DEFAULT = '',/g" ./api/twitch-v2-client/models/User.ts
```

Or alternatively you can use [openapi-typescript](https://github.com/DmitryScaletta/twitch-api-swagger?tab=readme-ov-file#typescript)

**Comment by MircoL** [comment]
Thank you for fixing the `User` issue.
And regarding the Enum, I will use your `sed` suggestion.
